RedHatInsights/patchman-ui

- config/rollup.config.js
- src/SmartComponents/AffectedSystems/AffectedSystems.js
- src/SmartComponents/SystemDetail/InventoryPage.js
- src/SmartComponents/Systems/Systems.js
This PR will allow importing only store without the component itself.
ping @jiridostal
> Split store when building to specific file so we have even better treeshaking

- src/PresentationalComponents/Filters/SearchFilter.js
- src/Utilities/api.js
fixes errors in console: 
1. res.json() is not a function error
2. Text input: Text input requires either an id or aria-label to be specified  error 
Before:
After:
> fix(api) res.json() is not a fucntion error fix

- src/Utilities/DataMappers.test.js
- src/Utilities/RawDataForTesting.js
- src/Utilities/api.js
- src/Utilities/api.test.js
- it seems that [fix(api) res.json() is not a fucntion error fix](https://github.com/RedHatInsights/patchman-ui/commit/277395626843a20cbed002b1d8011840926e2acb) was not a complete fix. I believe this PR has a complete fix.
- I was not able to implement some tests of functions in api.js file. They can not be tested as they call another function in the same file( [Problem definition](https://stackoverflow.com/questions/52650367/jestjs-how-to-test-function-being-called-inside-another-function) )
> chore(unit tests): for api.js and DataMappers.js`

- src/PresentationalComponents/TableView/TableView.js
fixes: [SPM-417](https://projects.engineering.redhat.com/browse/SPM-417)
> fix(AnsibleIcon) color changed to white

- src/App.js
fixes: [SPM-409](https://projects.engineering.redhat.com/browse/SPM-409)
> fix(ChromeNav) navigation is fixed on page change

- package-lock.json
- package.json
fixes: [SPM-423](https://projects.engineering.redhat.com/browse/SPM-423)
> fix(notifications): notifications has cancal button

- src/SmartComponents/SystemPackages/SystemPackages.js
- src/Utilities/DataMappers.js
Allow to select only package that have an update
> fix(select): disallow selection of non-updatable packages

- src/SmartComponents/SystemPackages/SystemPackages.js
resolves: [SPM-439](https://projects.engineering.redhat.com/browse/SPM-439)
> feat(SystemPackages):  empty state is added

- src/SmartComponents/AffectedSystems/AffectedSystems.js
- src/SmartComponents/Systems/Systems.js
- src/store/Reducers/InventoryEntitiesReducer.js
- src/store/Reducers/InventoryEntitiesReducer.test.js
- src/store/index.js
fixes: [SPM-396](https://projects.engineering.redhat.com/browse/SPM-396)
It looks a bit hackish. Improvements are appreciated ::)
> fix(LastSeen): sorting bug fix by displaying last_upload instead of updated

- src/PresentationalComponents/TableView/TableView.js
Fixes: [SPM-441](https://projects.engineering.redhat.com/browse/SPM-441)
> fix(RemediationIcon) color consistancy fix

- package-lock.json
- package.json
- src/SmartComponents/Advisories/Advisories.test.js
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/AdvisoryDetail/AdvisoryDetail.test.js
- src/SmartComponents/AdvisoryDetail/__snapshots__/AdvisoryDetail.test.js.snap
- src/SmartComponents/AffectedSystems/AffectedSystems.test.js
- src/SmartComponents/AffectedSystems/__snapshots__/AffectedSystems.test.js.snap
- src/Utilities/RawDataForTesting.js
- src/Utilities/unitTestingUtilities.js
resolves: [SPM-449](https://projects.engineering.redhat.com/browse/SPM-449)
> Unit test smart components advisories

- src/SmartComponents/AffectedSystems/AffectedSystems.js
fixes: [SPM-474](https://issues.redhat.com/browse/SPM-474)
> Fix remediation affected systems

- sitemap.xml
- src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
- src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
- src/SmartComponents/SystemDetail/InventoryPage.test.js
- src/SmartComponents/SystemDetail/SystemDetail.test.js
- src/SmartComponents/SystemDetail/__snapshots__/InventoryPage.test.js.snap
- src/SmartComponents/SystemDetail/__snapshots__/SystemDetail.test.js.snap
- src/Utilities/RawDataForTesting.js
- src/Utilities/unitTestingUtilities.js
resolves: [SPM-451](https://issues.redhat.com/browse/SPM-451)
> Unit tests SmartComponents/ SystemAdvisories.js + InventoryPage.js + SystemDetail.js

- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
- src/SmartComponents/SystemPackages/SystemPackages.js
- src/Utilities/Hooks.js
Part of: [SPM-614](https://issues.redhat.com/browse/SPM-614)
> chore(optimization): onSelect function is optimized

- src/PresentationalComponents/Snippets/AdvisoriesIcon.js
- src/PresentationalComponents/Snippets/DescriptionWithLink.js
- src/PresentationalComponents/Snippets/PackagesErrataLink.js
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
- src/Utilities/DataMappers.js
- src/Utilities/DataMappers.test.js
- src/Utilities/Helpers.js
- src/Utilities/__snapshots__/Helpers.test.js.snap
A partl of: [SPM-614](https://issues.redhat.com/browse/SPM-614)
> chore(optimization) some shared presentational components

- src/SmartComponents/SystemPackages/SystemPackages.test.js
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
- src/SmartComponents/Systems/SystemListAssets.test.js
- src/SmartComponents/Systems/Systems.test.js
resolves: [SPM-452](https://issues.redhat.com/browse/SPM-452)
> chore(unit tests): for System.js, SystemListAssets.js SystemPackages.js

- src/PresentationalComponents/Snippets/NoSystemData.js
- src/PresentationalComponents/Snippets/__snapshots__/NoSystemData.test.js.snap
resolves: [SPM-561](https://issues.redhat.com/projects/SPM/issues/SPM-561?filter=allopenissues)
> fix(NoSystemData): fix misleading wording

- src/PresentationalComponents/TableView/TableView.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
- src/SmartComponents/SystemPackages/SystemPackages.js
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
Fixes: https://ansible.slack.com/archives/CPS5FH07Q/p1606819639152400
> fix(globalFilter) error handling is fixed

- package.json
- src/Messages.js
https://issues.redhat.com/browse/SPM-605
> feat(internationalization): autogenerate translations

- src/App.js
> fix(nav): fix novaigation updates

- src/Messages.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/AdvisoryDetail/AdvisoryDetail.js
- src/SmartComponents/PackageDetail/PackageDetail.js
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/SystemDetail/InventoryPage.js
- src/SmartComponents/SystemDetail/__snapshots__/InventoryPage.test.js.snap
- src/SmartComponents/Systems/Systems.js
- src/Utilities/Hooks.js
- src/index.html
Titles and headers are now dynamic and correspond to UX doc.
> fix(titles): add dynamic titles

- config/dev.webpack.config.js
resolves: https://issues.redhat.com/browse/SPM-649
> chore(app): hot reload is enabled

- src/SmartComponents/Packages/Packages.js
- src/Utilities/api.js
resolves: https://issues.redhat.com/browse/SPM-650
> feat(Packages): add export feature

- src/Messages.js
- src/PresentationalComponents/AdvisoryHeader/AdvisoryHeader.js
- src/PresentationalComponents/AdvisoryHeader/__snapshots__/AdvisoryHeader.test.js.snap
- src/PresentationalComponents/Filters/PublishDateFilter.js
- src/PresentationalComponents/Filters/SearchFilter.js
- src/PresentationalComponents/Filters/StatusFilter.js
- src/PresentationalComponents/Filters/TypeFilter.js
- src/PresentationalComponents/RegisterPage/RegisterPage.js
- src/PresentationalComponents/Snippets/AdvisorySeverityInfo.js
- src/PresentationalComponents/Snippets/DescriptionWithLink.js
- src/PresentationalComponents/Snippets/EmptyStates.js
- src/PresentationalComponents/Snippets/Error.js
- src/PresentationalComponents/Snippets/NoAccess.js
- src/PresentationalComponents/Snippets/NoSystemData.js
- src/PresentationalComponents/Snippets/SystemUpToDate.js
- src/PresentationalComponents/Snippets/__snapshots__/EmptyStates.test.js.snap
- src/PresentationalComponents/TableView/TableView.js
- src/PresentationalComponents/TableView/TableViewAssets.js
- src/PresentationalComponents/TableView/__snapshots__/TableView.test.js.snap
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
resolves: https://issues.redhat.com/browse/SPM-607
> feat(internationalization): translate presentational components

- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/AdvisoryDetail/AdvisoryDetail.js
- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/PackageDetail/PackageDetail.js
- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
- src/SmartComponents/SystemPackages/SystemPackages.js
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
- src/SmartComponents/Systems/Systems.js
resolves: https://issues.redhat.com/browse/SPM-683
> feat(GenericError): use frontend components generic error component

- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/Remediation/RemediationModal.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemPackages/SystemPackages.js
- src/store/Reducers/SystemDetailStore.js
- src/store/Reducers/SystemDetailStore.test.js
Resolves: https://issues.redhat.com/browse/SPM-696.
1. Inventory has a problem to check if entity is defined.
2.  addNotifications import location is chaged.
> bug(pages): page breaking bugs resolved

- src/PresentationalComponents/TableView/TableViewAssets.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
- src/SmartComponents/Systems/Systems.js
- src/Utilities/DataMappers.js
- src/Utilities/DataMappers.test.js
> All tables should be compactfor ocnsistency

- src/PresentationalComponents/Filters/PackagesListStatusFilter.js
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
- src/Utilities/constants.js
- src/store/Reducers/PackagesListStore.js
Resolves: https://issues.redhat.com/browse/SPM-651 and https://issues.redhat.com/browse/SPM-697
> bug(StatusFilter): clear filters on unmount, solve 2x upgradable label

- src/SmartComponents/AdvisorySystems/AdvisorySystems.test.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
- src/SmartComponents/SystemDetail/InventoryPage.js
- src/SmartComponents/SystemPackages/SystemPackages.test.js
- src/Utilities/Helpers.js
- src/Utilities/Helpers.test.js
- src/Utilities/Hooks.js
- src/Utilities/RawDataForTesting.js
- src/store/Reducers/AdvisoryListStore.test.js
- src/store/Reducers/AdvisorySystemsStore.test.js
- src/store/Reducers/SystemAdvisoryListStore.test.js
fixes: https://issues.redhat.com/browse/SPM-733
> fix(bulkSelect): page selecting after selecting all items

- src/App.js
Resolves: https://ansible.slack.com/archives/G01NG0Y5RPA/p1613034742012100
> bug(App.js): change useEffect dependency to location.pathname

- package-lock.json
- package.json
- src/AppEntry.js
- src/store/index.js
Fixes chrome 2 redux compatibility issue.
Note that the systems table might still have an infinite loop. It will require some adjustments in the inventory component. We will fix it later.
cc @jiridostal @mkholjuraev
> Fix store already initialized error.

- .dependabot/config.yml
I would suggest changing dependabot update checking period to monthly.
> chore(dependabot): change update check to monthly

- src/Utilities/api.js
Fixes: 4th issue in the ticket (https://issues.redhat.com/browse/SPM-750)
> chore(CVEs): fix the url to /cves endpoint

- src/Routes.js
- src/SmartComponents/AdvisoryDetail/__snapshots__/AdvisoryDetail.test.js.snap
Resolves: https://issues.redhat.com/browse/SPM-759
> chore(Routes): remove the appended slash in URL

- src/Messages.js
- src/PresentationalComponents/TableView/TableViewAssets.js
- src/Utilities/DataMappers.js
resolves: https://issues.redhat.com/browse/SPM-761
> fix(CVEs): inconsistencies in cves info modal

- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemPackages/SystemPackages.js
resolves: https://issues.redhat.com/browse/SPM-732
> fix(select): after filering

- src/Messages.js
- src/PresentationalComponents/Filters/SearchFilter.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/AdvisoryDetail/CvesModal.js
- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemPackages/SystemPackages.js
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
- src/SmartComponents/Systems/Systems.js
Resolves: https://issues.redhat.com/browse/SPM-775
> fix(SearchFilter): wordings are made consistent with platform

- src/Messages.js
- src/SmartComponents/AdvisoryDetail/CvesModal.js
Resolves: https://issues.redhat.com/browse/SPM-778
> ficx(CVES): search filter is made case insensitive and wording fixed

- src/Messages.js
- src/SmartComponents/Systems/SystemsListAssets.js
- src/Utilities/DataMappers.js
- src/Utilities/Helpers.js
resolves: https://issues.redhat.com/browse/SPM-757
> feat(Systems): display OS version lock info

- src/Utilities/DataMappers.js
resolves: https://ansible.slack.com/archives/CPS5FH07Q/p1615962764009300
> chore(CVEs): change button to link

- src/SmartComponents/AdvisorySystems/AdvisorySystems.test.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
- src/SmartComponents/SystemDetail/SystemDetail.js
- src/Utilities/Helpers.js
- src/Utilities/Hooks.js
- src/Utilities/axiosInterceptors.js
resolves: https://issues.redhat.com/browse/SPM-792
SonarCube reliability bugs are fixed. Maintainability bugs will be fixed in the next PR
> fix(SonarCube): issues are resolved

- src/PresentationalComponents/TableView/TableView.js
- src/PresentationalComponents/TableView/__snapshots__/TableView.test.js.snap
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/Remediation/PatchRemediationButton.js
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
- src/SmartComponents/Systems/Systems.js
- src/Utilities/Helpers.js
- src/Utilities/api.js
- src/store/Reducers/SystemsListStore.js
This PR implement the Patch side of bulk remediation.
**There is a bug that prevents the remediation from creating - the wizard goes to the last step and than fails, platform is working on it**
The purpose is to demonstrate the behavior on Patch side.
> SPM-755 Add bulk remediation for systems and advisories

- src/Utilities/Helpers.js
> fix(OSLock): add undefined case

- package-lock.json
- package.json
fixes an issue with index.html file not replacing `@@env` placeholder when building.
cc @mkholjuraev
> Remove alpha html webpack plugin

- src/App.scss
- src/PresentationalComponents/AdvisoryType/AdvisoryType.js
- src/PresentationalComponents/AdvisoryType/__snapshots__/AdvisoryType.test.js.snap
- src/PresentationalComponents/Snippets/AdvisoriesIcon.js
- src/Utilities/Helpers.js
- src/Utilities/__snapshots__/Helpers.test.js.snap
I  was not aware that Patternfly flex component has a no-wrap style option. Also applicable advisories column is made no-wrap on scroll
> chore(Advisories): SPM-837 better implementation

- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/Systems/Systems.js
This should prevent broken columns when the updated inventory table arrived
> Disable defaultColumns in inventory table

- src/SmartComponents/PackageDetail/PackageDetail.js
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
- src/SmartComponents/SystemPackages/SystemPackages.js
- src/SmartComponents/SystemPackages/SystemPackages.test.js
- src/Utilities/DataMappers.js
Notifications middleware is already displaying an error notification every time there is an error. So, duplicate notification was being displayed from Patch.
> chore(notifications): removed unnecessary notifications and some cleanup

- src/Utilities/DataMappers.js
To fix the problem with disableCheckbox in package systems table
> fix(PackageSystems): updatable key is added into reducer

- src/Utilities/Helpers.js
It looks this one line fix solves the issue
> fix(GlobalFilter): SPM-1041 tags applied on load

- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemPackages/SystemPackages.js
- src/store/Reducers/SystemAdvisoryListStore.js
- src/store/Reducers/SystemPackageListStore.js
This reverts commit 9c61e722363f6304d9e319bd5438ed7adb08b0cb.
> fix(revert): System details do not clear parameters on umount

- package-lock.json
- package.json
- src/App.scss
- src/Utilities/DataMappers.js
- src/Utilities/DataMappers.test.js
- src/Utilities/Helpers.js
https://user-images.githubusercontent.com/59481011/129541935-0429e4be-3287-49d9-91ae-0878b305e47c.mp4
> fix(Synopsis) SPM-1078 synopsis is truncated

- package-lock.json
- src/AppEntry.js
As chrome 2 is already everywhere, we can remove this
> chore(AppEntry): remove obsolete code

- src/PresentationalComponents/AdvisoryType/AdvisoryType.js
- src/PresentationalComponents/AdvisoryType/__snapshots__/AdvisoryType.test.js.snap
- src/PresentationalComponents/StatusReports/AdvisoriesStatusReport.js
After the PR changes:
https://user-images.githubusercontent.com/59481011/150975783-040a5d5d-6e46-4714-99b4-86dcbe9f7eaf.mp4
> SPM-1321: make advisory cards responsive

- src/PresentationalComponents/StatusReports/AdvisoriesStatusReport.js
- src/PresentationalComponents/StatusReports/SystemsStatusReport.js
- src/SmartComponents/Systems/__snapshots__/System.test.js.snap
Advisories:
- Before
- After
Systems:
- Before
- After
> fix(SPM-1358): Fixed responsiveness issues on dashbars

- src/SmartComponents/SystemDetail/InventoryDetail.js
This ticket is in a wrong project: ADVISOR-1964
New look
> fix(InventoryDetail): Changed Alert to inline

- README.md
README now corresponds to https://github.com/RedHatInsights/patchman-ui/pull/752
> Update README with latest build config

- src/App.js
- src/Utilities/Helpers.js
- src/Utilities/Helpers.test.js
resolves: https://issues.redhat.com/browse/RHIF-22
> feat(RHIF-22): enable AAP & MSSQL fitlers

- src/SmartComponents/SystemDetail/InventoryDetail.js
- src/SmartComponents/SystemDetail/InventoryDetail.test.js
- src/SmartComponents/SystemDetail/__snapshots__/InventoryDetail.test.js.snap
This adds assign patch set action in System details header actions dropdown.
> feat(SPM-1311): assign systems to a patch-set in System details page

- package-lock.json
- package.json
Fixes:
https://issues.redhat.com/browse/SPM-1428
https://issues.redhat.com/browse/SPM-1429
https://issues.redhat.com/browse/SPM-1430
> chore: Bump frontend-components-config

- build_deploy.sh
- package.json
- pr_check.sh
Add pr_check.sh and build_deploy.sh files for containerizing the application. 
For more info: https://consoledot.pages.redhat.com/docs/dev/getting-started/frontend-migration.html#_pr_check
> Containerize app

- src/Messages.js
- src/SmartComponents/PatchSet/PatchSetAssets.js
- src/SmartComponents/PatchSetWizard/InputFields/DescriptionField.js
- src/SmartComponents/PatchSetWizard/InputFields/NameField.js
- src/SmartComponents/PatchSetWizard/InputFields/ToDateField.js
- src/SmartComponents/PatchSetWizard/steps/RequestProgress.js
- src/SmartComponents/PatchSetWizard/steps/ReviewPatchSet.js
- src/SmartComponents/PatchSetWizard/steps/__snapshots__/ReviewPatchSet.test.js.snap
Internationalizes texts on Patch template with text render optimization.
> chore(PatchTemplate): internationalize wizard, optimize text rendering

- src/Messages.js
- src/SmartComponents/PatchSetWizard/steps/RequestProgress.js
> chore(RequestProgress): fix contact support link

- src/SmartComponents/PackageSystems/PackageSystems.js
With this commit, remediation should work as expected.
> fix(select): SPM-1418 Fix selection on PackageSystems

- src/PresentationalComponents/TableView/TableView.test.js
- src/PresentationalComponents/TableView/__snapshots__/TableView.test.js.snap
- src/SmartComponents/AdvisorySystems/__snapshots__/AdvisorySystem.test.js.snap
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
- src/SmartComponents/Systems/__snapshots__/System.test.js.snap
- src/Utilities/Hooks.js
This introduces a loading icon when all entities are selected using the bulk selector.
> fix(BulkSelect): enable loading state when all entities selected

- src/Utilities/api.js
Resolves: https://issues.redhat.com/browse/SPM-1584
A simple PR to use api version 2.
> Use api v2

- src/Utilities/DataMappers.js
- src/Utilities/Helpers.js
This PR fixes the 'Last seen' column sorting by using the column properties from the Inventory component.
> fix(Systems): fixes sorting last seen column

- src/SmartComponents/PackageSystems/PackageSystems.js
resolves: https://issues.redhat.com/browse/SPM-1802.
to test:
1. visit pakcages pae.
2. open a package in the table
3. select updatable systems
4. click on remediate button
5. observe that remediation modal is loaded
> fix(SPM-1802): fix remediation provider for package systems

- src/SmartComponents/Packages/__snapshots__/Packages.test.js.snap
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
- src/SmartComponents/SystemPackages/SystemPackages.test.js
- src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
- src/Utilities/DataMappers.test.js
- src/Utilities/RawDataForTesting.js
- src/Utilities/__snapshots__/DataMappers.test.js.snap
- src/Utilities/useOnSelect.js
Associated Jira ticket: [SPM-1812](https://issues.redhat.com/browse/SPM-1812)
This fixes the single-row selection on the system packages table. 
1. Visit the systems page
2. Click on any system that has an upgradable package
3. Click on the Packages tab
4. Observe that bulks select is still working
5. Observe that a single row is also fixed. 
6. Observe that remediation works with selected row(s) that are selected using single-row selection
7. Observe that system advisory remediation is not broken
No snapshot is needed.
No snapshot is needed.
> fix(SPM-1812): fix system package single row selection

- .travis.yml
Fixes failing build by inserting gh token into travis env to give an write access to semantic release
> fix(semantic-release): gh token is added

- src/App.scss
- src/PresentationalComponents/StatusReports/AdvisoriesStatusReport.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/Advisories/Advisories.test.js
- src/Utilities.scss
> chore: do not wait advisories to display most impactfull statistics

- src/App.js
Associated Jira ticket: # [SPM-1857](https://issues.redhat.com/browse/SPM-1857)
fixes the global filter in the app by changing the equal sign to not equal. the regression appeared when i worked on refactor.
Play with the global filter and verify it is working.
> fix(SPM-1857): change global comparision to not equal sign

- src/SmartComponents/Systems/SystemsListAssets.js
- src/Utilities/DataMappers.js
Associated Jira ticket: [SPM-1892](https://issues.redhat.com/browse/SPM-1892)
Mockup: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/DP7Ka9y
Display 'No template' instead of blank cell in template column in System list table
Verify correspondence with the mockup.
> fix: Display 'No template' instead of blank cell in template column

- src/Messages.js
- src/PresentationalComponents/Snippets/EmptyStates.js
- src/SmartComponents/PatchSet/PatchSet.js
- src/SmartComponents/PatchSet/__snapshots__/PatchSet.test.js.snap
- src/Utilities/DataMappers.js
Associated Jira ticket: [SPM-1892](https://issues.redhat.com/browse/SPM-1892)
Mockup: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/25O3lOp
Update Template list page empty state according to the mockup.
Verify correspondence of Templates page when there are 0 templates present to the mockup.
> feat(Templates): Update Template list page empty state

- src/Messages.js
- src/SmartComponents/PatchSet/__snapshots__/PatchSet.test.js.snap
- src/SmartComponents/PatchSetWizard/PatchSetWizard.js
- src/SmartComponents/PatchSetWizard/WizardAssets.js
- src/SmartComponents/PatchSetWizard/steps/ReviewPatchSet.js
- src/SmartComponents/PatchSetWizard/steps/__snapshots__/ReviewPatchSet.test.js.snap
- src/Utilities/DataMappers.js
Update template wizard review step (3rd step) according to the [mockups](https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/Qbnd821).
This change is WIP and will be split into multiple PRs.
Check if the code is acceptable.
> feat: Update template wizard review step

- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
- src/SmartComponents/PatchSetDetail/PatchSetDetailAssets.js
- src/Utilities/DataMappers.js
- src/Utilities/Helpers.js
- src/Utilities/Hooks.js
- src/Utilities/SystemsHelpers.js
- src/Utilities/constants.js
Associated Jira ticket: [SPM-1930](https://issues.redhat.com/browse/SPM-1930)
Mockup: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/DP7Ka9y
It's still missing tags column and OS column is not sortable, but we will add it as a part of another ticket.
> Populate template assigned systems table

- src/Messages.js
- src/PresentationalComponents/Filters/CreatorFilter.js
- src/SmartComponents/PatchSet/PatchSet.js
- src/SmartComponents/PatchSet/__snapshots__/PatchSet.test.js.snap
- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
- src/Utilities/constants.js
Associated Jira ticket: [SPM-1932](https://issues.redhat.com/browse/SPM-1932)
Add 'Creator' checkbox filter to Template list page. The options are sent from the backend inside meta section of API response and then saved inside Template list store.
> Add 'Creator' filter to Template list page

- babel.config.js
- config/dev.webpack.config.js
- config/prod.webpack.config.js
- package-lock.json
- package.json
- src/PresentationalComponents/Snippets/EmptyStates.js
- src/PresentationalComponents/Snippets/Error.js
- src/PresentationalComponents/Snippets/ExternalLink.js
- src/PresentationalComponents/TableView/TableViewAssets.js
- src/SmartComponents/PatchSet/PatchSetAssets.js
- src/SmartComponents/Remediation/AsyncRemediationButton.js
- src/Utilities/Helpers.js
- src/Utilities/Helpers.test.js
- src/Utilities/Hooks.js
- src/Utilities/Hooks.test.js
- src/Utilities/constants.js
This PR disables loading `@patternfly/react-icons`,` @patternfly/react-table` packages, but forces to load the shared deps from the default scope in federated module. With this in place, dependant apps, will not load their local copy of the package, but use the shared one as both a fallback module and main instance in the shared scope. This PR, should be looked at together with this demo Patch PR.
> Bundle size

- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/Systems/System.test.js
- src/SmartComponents/Systems/SystemListAssets.test.js
- src/SmartComponents/Systems/Systems.js
- src/SmartComponents/Systems/SystemsListAssets.js
- src/SmartComponents/Systems/__snapshots__/System.test.js.snap
- src/Utilities/DataMappers.js
- src/Utilities/SystemsHelpers.js
- src/Utilities/api.js
Associated Jira ticket: [SPM-1956](https://issues.redhat.com/browse/SPM-1956) [SPM-1959](https://issues.redhat.com/browse/SPM-1959)
Mockups: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/Om3zKYq
- changed /systems API from v2 to v3
- this adds new `baseline_id` parameter to the response from which link to Template detail can be correctly created
- simplifies OS parameters into one
- System list table
- replace "Applicable advisories" column with "Installable advisories" column
- rename "Packages" column to "Installed packages"
- change the order of the columns according to the mockups
- move "Assign to a template" button into the toolbar kebab
- Advisory systems table
- removed packages and applicable advisories columns
> Update System list page to the latests mockups

- src/PresentationalComponents/Filters/CreatorFilter.js
Please see comment in [SPM-1932](https://issues.redhat.com/browse/SPM-1932).
> Fix creator filter

- src/SmartComponents/Systems/Systems.js
- src/SmartComponents/Systems/__snapshots__/System.test.js.snap
https://redhat-internal.slack.com/archives/CPS5FH07Q/p1679499017978129
> Fix Remediation button missing when Template FF was false

- src/Routes.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/Systems/Systems.js
- src/Utilities/constants.js
- src/Utilities/useRemediationDataProvider.js
> fix: remaining insights.chrome references

- src/SmartComponents/Modals/UnassignSystemsModal.test.js
- src/SmartComponents/Modals/useUnassignSystemsHook.js
- src/Utilities/Hooks.js
- src/Utilities/api.js
There should be no change in functionality.
> Update all remaining template API endpoints to v3

- src/store/Reducers/SystemDetailStore.js
Associated Jira ticket: [SPM-2003](https://issues.redhat.com/browse/SPM-2003)
> Fix adding/removing template not causing refresh in System detail header

- src/SmartComponents/Systems/Systems.js
Associated Jira ticket: [SPM-2004](https://issues.redhat.com/browse/SPM-2004)
> Fix System list not refreshing after template assignment/removal

- src/SmartComponents/Systems/SystemsListAssets.js
Part of https://issues.redhat.com/browse/SPM-1949
> Add sort to status column in Advisory systems table

- src/PresentationalComponents/Filters/AdvisoryStatusFilter.js
- src/PresentationalComponents/Filters/AdvisoryStatusFilter.test.js
- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/AdvisorySystems/__snapshots__/AdvisorySystem.test.js.snap
- src/SmartComponents/SystemAdvisories/SystemAdvisories.js
- src/Utilities/constants.js
Part of https://issues.redhat.com/browse/SPM-1949
> Add status filter to Advisory systems table

- src/Messages.js
- src/SmartComponents/PatchSetWizard/InputFields/ConfigurationFields.js
- src/SmartComponents/PatchSetWizard/PatchSetWizard.js
- src/SmartComponents/PatchSetWizard/WizardAssets.js
- src/SmartComponents/PatchSetWizard/steps/ConfigurationStepFields.js
- src/SmartComponents/PatchSetWizard/steps/ContentStep.js
- src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
Part of: https://issues.redhat.com/browse/SPM-1976
Mockups: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/zxrAJZy#Inspect
> Split first step of Template Wizard into two steps

- src/Messages.js
- src/PresentationalComponents/Snippets/EmptyStates.js
- src/PresentationalComponents/Snippets/EmptyStates.test.js
- src/PresentationalComponents/Snippets/__snapshots__/EmptyStates.test.js.snap
- src/SmartComponents/PatchSet/PatchSet.js
- src/SmartComponents/PatchSet/PatchSet.test.js
- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
https://issues.redhat.com/browse/SPM-2025
> Templates don't require Smart Management

- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/PackageSystems/PackageSystems.test.js
- src/store/Reducers/InventoryEntitiesReducer.js
https://issues.redhat.com/browse/SPM-2046
- selecting systems one by one in the package detail page and then clicking remediate would crash the remediation wizard
- bulk selecting page/all worked fine
- selecting systems and remediating should work correctly
- try to remediate some systems in the package detail page
- try selecting systems one by one, bulk selecting, deselecting one by one and various combinations of these
> Fix remediation not working in the package detail page

- src/Messages.js
- src/PresentationalComponents/PatchSetWrapper/PatchSetWrapper.js
- src/PresentationalComponents/PatchSetWrapper/PatchSetWrapper.test.js
- src/SmartComponents/Modals/AssignSystemsModal.js
- src/SmartComponents/Modals/UnassignSystemsModal.test.js
- src/SmartComponents/Modals/useUnassignSystemsHook.js
- src/SmartComponents/PatchSet/PatchSetAssets.js
- src/SmartComponents/PatchSetWizard/InputFields/SelectExistingSets.js
- src/SmartComponents/PatchSetWizard/InputFields/SelectExistingSets.test.js
- src/SmartComponents/PatchSetWizard/steps/ConfigurationStepFields.js
- src/SmartComponents/Systems/System.test.js
- src/SmartComponents/Systems/Systems.js
- src/SmartComponents/Systems/SystemsListAssets.js
- src/Utilities/Helpers.js
- src/Utilities/Hooks.js
- src/Utilities/constants.js
- src/Utilities/usePatchSetState.js
Add a new modal when assigning systems to template from System list page
Mockups: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/Om3zKYq#Inspect
So far it's not 100% according to the mockups, but it's good a large step in the right direction.
> Add template assign modal

- src/SmartComponents/PatchSetWizard/InputFields/SelectExistingSets.js
- src/SmartComponents/SystemDetail/InventoryDetail.js
Same as #1044 but for System detail page when you click `Assign to a template` from header dropdown
> Add template assignment modal to system detail page

- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
Fixes https://issues.redhat.com/browse/SPM-2060
> Clear Inventory store upon exiting Template detail page

- src/App.js
This enables debugging shared scope and to get info on what app is loaded multiple times. The information is displayed in the warnings
> chore: enable warning duplicate shared packages

- .travis/custom_release.sh
> temp: see what are there in ./dist folder while build pipeline

- src/Messages.js
- src/PresentationalComponents/TableView/TableViewAssets.js
- src/SmartComponents/Packages/__snapshots__/Packages.test.js.snap
- src/Utilities/DataMappers.js
Ticket: https://issues.redhat.com/browse/SPM-1950
> Update packages table columns

- package-lock.json
- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
- src/Utilities/Hooks.js
- src/Utilities/SystemsHelpers.js
Adds tag, OS and System name filters to Template detail page.
> Add filters to Template detail page

- config/setupTests.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/AdvisoryDetail/AdvisoryDetail.js
- src/SmartComponents/PackageDetail/PackageDetail.js
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/PatchSet/PatchSet.js
- src/SmartComponents/SystemDetail/InventoryDetail.js
- src/SmartComponents/Systems/Systems.js
- src/Utilities/Hooks.js
- src/Utilities/constants.js
A partial cause of https://issues.redhat.com/browse/RHIF-207 is that the document title isnt updated properly. This PR introduces the chrome hook.
Associated Jira ticket: # (RHIF-266)
Navigate to all pages and verify that the document changes appropriately
> fix(RHIF-264):  adopt useChrome updateDocumentTitle hook

- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
Previously the Template name was not reflected in the title.
> Set page title from Template detail page

- src/App.scss
Associated Jira ticket: [ESSNTL-5086](https://issues.redhat.com/browse/ESSNTL-5086)
Before:
After:
Go to Patch > Systems > Tag filter and make sure it looks correct
> fix(ESSNTL-5086): Tags filter UI issue

- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/AdvisorySystems/__snapshots__/AdvisorySystem.test.js.snap
- src/SmartComponents/Systems/SystemsListAssets.js
- src/SmartComponents/Systems/__snapshots__/System.test.js.snap
- src/Utilities/DataMappers.js
https://issues.redhat.com/browse/SPM-2143
If system status is Installable the kebab should be enabled.
> Disable row kebab on Advisory Systems table when system is Applicable

- src/Utilities/SystemsHelpers.js
https://issues.redhat.com/browse/SPM-2176
> Fix system name links not working

- src/Messages.js
- src/SmartComponents/SystemDetail/InventoryDetail.js
- src/store/Reducers/SystemDetailStore.js
Jira ticket: https://issues.redhat.com/browse/RHINENG-2487
Mockup: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/vRxbVR3
> Update banner text shown on System detail of Satellite managed system

- src/Messages.js
- src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
Ticket: https://issues.redhat.com/browse/RHINENG-2488
Mockup: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/nQgolnz#Inspect
Note: Mockups do not look exactly as Patchman, I only added the new sentences.
Also added missing margin between title and text.
> Update text in Template wizard > System review step

- src/SmartComponents/AdvisorySystems/AdvisorySystems.js
- src/SmartComponents/AdvisorySystems/__snapshots__/AdvisorySystem.test.js.snap
- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
- src/SmartComponents/Systems/Systems.js
- src/SmartComponents/Systems/__snapshots__/System.test.js.snap
- src/Utilities/Helpers.js
- src/Utilities/Helpers.test.js
- src/Utilities/Hooks.js
- src/Utilities/SystemsHelpers.js
Associated Jira ticket: #RHINENG-2912
Removes the custom handling for the OS filter for InventoryTables
https://github.com/RedHatInsights/patchman-ui/assets/7757/2c301da9-6150-41df-8690-42022b7de260
https://github.com/RedHatInsights/patchman-ui/assets/7757/1a348481-62b6-4c56-8d4e-15933b5590b8
> fix(InventoryTable): RHINENG-2912 - Remove custom OS filter handling

- src/Utilities/Helpers.js
- src/Utilities/Hooks.js
Ticket: https://issues.redhat.com/browse/RHINENG-3122
Fix the timezone bug by setting the up to date time as the next local timezone midnight minus one second (23:59:59).
> Fix template up-to date being 1 day off on west hemisphere

- src/SmartComponents/SystemDetail/InventoryDetail.js
Associated Jira ticket: [RHINENG-3659](https://issues.redhat.com/browse/RHINENG-3659)
Also open the link in a new tab.
> Update Satellite docs link

- src/Utilities/Hooks.js
Associated Jira ticket: #RHINENG-2396 
This prevents patch from updating its state and the URL parameters if the component/hook got unmounted while it was fetching systems from the API
1) Navigate to the Patch -> Systems page
2) As soon as the page loads and the InventoryTable appears in the loading state navigate away to a different page.
Without preventing the state/URL updates Patch will reappear again once the fetching of systems completed.
The patch systems page does not reappear.
> fix(SystemsTable): RHINENG-2396 - Prevent state & URL updates when not mounted

- config/rtlwrapper.js
- config/setupTests.js
- src/PresentationalComponents/Filters/OsVersionFilter.test.js
- src/PresentationalComponents/PatchSetWrapper/PatchSetWrapper.test.js
- src/SmartComponents/PatchSetWizard/InputFields/ConfigurationFields.js
- src/SmartComponents/PatchSetWizard/InputFields/ConfigurationFields.test.js
- src/SmartComponents/PatchSetWizard/InputFields/ToDateField.test.js
- src/SmartComponents/SystemDetail/SystemDetail.js
- src/SmartComponents/SystemDetail/SystemDetail.test.js
- src/SmartComponents/SystemDetail/__snapshots__/SystemDetail.test.js.snap
Refactoring the last enzyme tests
Current issues:
> feat(test): Enzyme refactor part 3

- src/Messages.js
- src/SmartComponents/PatchSetWizard/InputFields/NameField.js
- src/SmartComponents/PatchSetWizard/WizardAssets.js
https://redhat-internal.slack.com/archives/C02T90PLJ5V/p1707755885806079
> fix: Remove template name regex restriction

- package-lock.json
https://issues.redhat.com/browse/RHINENG-8451
> chore(deps): Update sanitize-html to fix CVE

- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/AdvisoryDetail/AdvisoryDetail.js
- src/SmartComponents/PackageDetail/PackageDetail.js
- src/SmartComponents/Packages/Packages.js
- src/SmartComponents/PatchSet/PatchSet.js
- src/SmartComponents/PatchSetDetail/PatchSetDetail.js
- src/SmartComponents/SystemDetail/InventoryDetail.js
- src/SmartComponents/Systems/SystemsPage.js
- src/Utilities/constants.js
Associated Jira ticket: # https://issues.redhat.com/browse/RHINENG-9387
Updates page titles according to 'Current concept' column, single line treatment in this [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)
> chore(RHINENG-9387): update page titles

- src/PresentationalComponents/Filters/PublishDateFilter.js
- src/PresentationalComponents/Filters/PublishDateFilter.test.js
https://issues.redhat.com/browse/RHINENG-10234
> Fix publish date filter all option not working

- package-lock.json
- package.json
> chore(RHINENG-10336): update cypress code-cov package

- src/PresentationalComponents/Snippets/ExternalLink.js
- src/SmartComponents/Advisories/Advisories.js
- src/SmartComponents/SystemDetail/__snapshots__/SystemDetail.test.js.snap
https://issues.redhat.com/browse/RHINENG-14775
> feat(Advisories header): Add tooltip with documentation

- .github/workflows/sentry.yml
- .gitignore
- fec.config.js
- package-lock.json
- package.json
This onboards Patchman to sentry to receive proper error reporting/routing, as well as the automation workflow that sends debugIDs up on a merge to master + sourceMap automation when a release is made too prod
> feat(RHINENG-15384): Onboard Patchman to Sentry instance

- renovate.json
> feat(Konflux): Enable automerge

- .github/CODEOWNERS
> chore(Konflux): Remove condeowners for Konflux automerge

- .gitmodules
- .tekton/patchman-ui-pull-request.yaml
- .tekton/patchman-ui-push.yaml
Associated Jira ticket: [RHINENG-16159](https://issues.redhat.com/browse/RHINENG-16159)
> chore(build): use shared Dockerfile

- src/Messages.js
Changes the text in remediations button to Plan remediation
https://issues.redhat.com/browse/RHINENG-16658
This button is found here: 
Content --> Advisories
Content --> Advisories --> (select an advisory)
Content --> Systems
> feat(RHINENG-16658): Update Remediation button name

- src/SmartComponents/AdvisorySystems/AdvisorySystemsTable.js
- src/SmartComponents/PackageSystems/PackageSystems.js
- src/SmartComponents/Systems/SystemTable.test.js
- src/SmartComponents/Systems/SystemsListAssets.js
- src/SmartComponents/Systems/SystemsTable.js
- src/Utilities/hooks/Hooks.js
https://issues.redhat.com/browse/RHINENG-15598
> feat(RHINENG-15598): Add column management to Patch InventoryTable tables

- src/SmartComponents/Advisories/Advisories.js
> fix(RHINENG-20817): Add missing space to popover

- deploy/frontend.yml
This migrates our frontend deployment config to use the new schema for the frontend operator (FEO).
Associated Jira ticket: [#RHINENG-17218](https://issues.redhat.com/browse/RHINENG-17218)
> RHINENG-17218: feo migration
