RedHatInsights/patchman-ui

src/SmartComponents/AffectedSystems/AffectedSystems.js
src/SmartComponents/SystemDetail/InventoryPage.js
src/SmartComponents/Systems/Systems.js

We are working on inventory refactoring, since we'd like to fully use hooks and such we have to use App's react dependency. With this being used react-redux needs to be passed from application as well. If you are cautious about the size of your bundle I can pick only the functions really required by inventory.

feat(inventory): pass react-redux to inventory

---

package-lock.json
package.json
src/SmartComponents/AffectedSystems/AffectedSystems.js
src/SmartComponents/SystemDetail/InventoryPage.js
src/SmartComponents/Systems/Systems.js

There is a new feature brewing in chrome, building chrome with webpack [1]. This PR passes newly required dependencies. In future we'll use Federated modules [2] so there won't be a need for these changes, but this is required as a mid-step solution.
Also, for enabling A/B testing of inventory detail we are working on new inventory component, for now this component will be undefined so use `React.Fragment` as fallback.
[1] https://github.com/RedHatInsights/insights-chrome/pull/842
[2] https://webpack.js.org/concepts/module-federation/

Pass pf react core to inventory to properly render inventory

---

src/SmartComponents/Systems/Systems.js

In order to show proper RBAC state in systems table we need to pass `fullView` prop to inventory component. This applies only to systems page as it's the only place where inventory table is just one component on screen. Without this prop the `unAuthorized` component would be in table, which is not correct based on our mocks.
[1] https://github.com/RedHatInsights/frontend-components/blob/master/packages/inventory/doc/inventory.md#using-rbac-with-inventory

Mark systems table as full view

---

src/SmartComponents/SystemDetail/InventoryPage.js

Fixes: [the infinite re - rendering issue](https://ansible.slack.com/archives/CPS5FH07Q/p1601014601017800?thread_ts=1601014582.017700&cid=CPS5FH07Q).
I noticed that SystemAdvisories component is rendering infinite times. I believe that there was some changes in dependencies and all setStates inside fetchInventory function is causing race condition. I deleted the last setInventoryWrapper and it solved the issue. But I am not sure if this is the optimal solution.

Fix system details page

---

src/App.js

When navigating to patch and then to any other app it shows the global filter no matter if we hid it or not. This is caused by using `insights.chrome.enable.globalFilter();`, this function should be used only for local debugging and not stored in your code, it'll set localStorage value which enables global filter everywhere.

Remove debug enable function from patch component mount

---

src/PresentationalComponents/Filters/PublishDateFilter.js
src/PresentationalComponents/Filters/PublishDateFilter.test.js
src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
src/Utilities/constants.js

not a complete solution [SPM-614](https://issues.redhat.com/browse/SPM-614) 
But using this approach we could avoid 
`    // Empty string value is not supported by PF Radio at the moment
if (currentValue === '' || !currentValue) {
currentValue = '0';
}`

fix(ConditionalFilter): radio type filter empty value is fixed

---

src/PresentationalComponents/Header/Header.js
src/PresentationalComponents/Header/HeaderBreadcrumbs.js
src/PresentationalComponents/Header/HeaderTabs.js
src/PresentationalComponents/Header/__snapshots__/Header.test.js.snap
src/PresentationalComponents/TableView/TableFooter.js
src/PresentationalComponents/TableView/TableView.js
src/PresentationalComponents/TableView/__snapshots__/TableView.test.js.snap
src/SmartComponents/Advisories/Advisories.js
src/SmartComponents/Advisories/__snapshots__/Advisories.test.js.snap
src/SmartComponents/AdvisoryDetail/AdvisoryDetail.js
src/SmartComponents/AdvisoryDetail/__snapshots__/AdvisoryDetail.test.js.snap
src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/PackageDetail/PackageDetail.js
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/Packages/Packages.js
src/SmartComponents/SystemAdvisories/SystemAdvisories.js
src/SmartComponents/SystemAdvisories/__snapshots__/SystemAdvisories.test.js.snap
src/SmartComponents/SystemDetail/InventoryPage.js
src/SmartComponents/SystemDetail/SystemDetail.js
src/SmartComponents/SystemDetail/__snapshots__/InventoryPage.test.js.snap
src/SmartComponents/SystemDetail/__snapshots__/SystemDetail.test.js.snap
src/SmartComponents/SystemPackages/SystemPackages.js
src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
src/SmartComponents/Systems/Systems.js

Partial work for: [SPM-580](https://issues.redhat.com/browse/SPM-580)
What components have OUIA enabled:
1.  Tables not including Inventory. e.g `data-ouia-component-id="advisories-table"`
2.  actionsConfig of PrimaryToolbar. e.g remediation button `data-ouia-component-id="toolbar-remediation-button"`  
3. bulkSelect toggle button of PrimaryToolbar.  `data-ouia-component-type="bulk-select-toggle-button"`
4. Header of all pages. e.g `data-ouia-component-type="advisory-details-page-header"`
5. Header breadcrumbs. e.g `data-ouia-component-type="advisory-details-breadcrumb" ` `data-ouia-component-id="breadcrumb-to-Advisories"` 
6. Header tabs. e.g `data-ouia-component-type="advisory-details-breadcrumb" ` `data-ouia-component-id="breadcrumb-to-Advisories"`
What is missing : 
1. Primary toolbar …

feat(OUIA): enable OUIA for Patch

---

.dependabot/config.yml

I would suggest extending the update checking period from _live_ to _weekly_ so that we do not have every version updates which ends up with a lot of PRs opened.

chore(dependabot): extend the update checking period

---

src/Routes.js

Since we are in SPA now InsightsRoute is redundant and only the `Route` from `react-router-dom` can be used.

Remove insights route as it can cause page break

---

src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/Packages/Packages.js
src/SmartComponents/SystemAdvisories/SystemAdvisories.js
src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
src/SmartComponents/SystemPackages/SystemPackages.js
src/SmartComponents/SystemPackages/SystemPackages.test.js
src/SmartComponents/Systems/SystemListAssets.test.js
src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/Helpers.js
src/Utilities/Helpers.test.js
src/Utilities/constants.js

Resolves: https://issues.redhat.com/browse/SPM-737
- I think we have only 2 usages of remediation (remediation advisories, and remediation packages). Thus I did want to touch on existing, already working code. Instead created a special case for remediating packages.
- some unused code is removed from Packages component

feat(Packages): change remediation identifier to patch-package

---

src/Utilities/DataMappers.js
src/Utilities/Helpers.js

Patch engine has changed API response object key name from rhsm_version to rhsm. We also need to make some changes

fix(OSLock): change rhsm_version object key name to rhsm

---

.cz-config.js
README.md
package-lock.json
package.json

This is a test PR from using commitizer for the ticket https://issues.redhat.com/browse/SPM-769
[cz-cli](https://github.com/commitizen) has several steps to finish the commit e.g type, scope, footer .... I thought some of them are unnecessaryy, thus I used [cz-customizable](https://github.com/leonardoanalista/cz-customizable) with custom config which can be improved according to needs later.

SPM-769  feat(git commits): use commitizer to enable conventionam commit naming

---

src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/Systems/Systems.js
src/Utilities/api.js

Resolves: https://issues.redhat.com/browse/SPM-754
I am not sure if I have achieved everything that is wanted. As per slack conversation, we could get rid of InventoryEntitiesReducer. But when I removed the store, the Inventory table keeps loading with the error: 'page is not identified'

feat(InventoryComp): use customFetch

---

src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/Systems/Systems.js
src/Utilities/Helpers.js
src/Utilities/Hooks.js

cc @mkholjuraev 
This PR fixes an issue when the inventory table hangs in a loading state.
The problem was caused by duplicate API calls by the `getEntities` and `onRefresh` callbacks. Where possible, I've integrated the onRefresh into the `getEntities` callback which will prevent double calls and hanging loading state in the entities reducer.
@mkholjuraev Please double-check that nothing broke with this change.

Integrate handle refresh into getEntities.

---

src/PresentationalComponents/Snippets/AdvisoriesIcon.js
src/SmartComponents/Systems/Systems.js

Systems, advisory details page breaks after clicking 'Clear filters' button due to initial undefined data

fix(Inventory): fix clear filters issue after custom inventory fetch

---

src/SmartComponents/PackageDetail/PackageDetail.js
src/store/Reducers/AdvisoryDetailStore.js
src/store/Reducers/AdvisoryDetailStore.test.js
src/store/Reducers/PackageDetailStore.js

Continuously loading headers are fixed in advisory detail and package detail page.

fix(Headers): isLoading is set correctly

---

src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/Systems/Systems.js
src/Utilities/Helpers.js
src/store/Reducers/InventoryEntitiesReducer.js

The issues after rebase:
1. `filterSelectedRowIDs` function in Helpers.js was renamed to `removeUndefinedObjectKeys`. But this change was got lost during rebase and it was not reflected in Inventory Components.
2. `useEffect` in PackageSystems page was changed to async function and it broke the implementation of `clearInventoryReducer`. Thus if you select a system on the Package Systems page it was present also in Systems Page. 
3. If you select All systems, all of the systems on the first page is selected even if it was selected. It was because we did not call the `inventoryModifier` reducer to remap with updated systems selected.
4. The last problem that occurred was the incorrect `useSelector` for selected rows in all Inventory pages. Previously `selectedRows` was a part of the …

fix(Inventory): problems after rebase are solved

---

package-lock.json
package.json
src/PresentationalComponents/Filters/VersionFilter.js
src/SmartComponents/SystemAdvisories/SystemAdvisories.js
src/SmartComponents/SystemPackages/SystemPackages.js
src/Utilities/Helpers.js
src/Utilities/Hooks.js
src/store/Reducers/SystemAdvisoryListStore.js
src/store/Reducers/SystemPackageListStore.js

The PR includes 2 fixes for the release: 
1. Broken page after reload because of difference between how installed_evra is decoded from URL params. installed_evra gets decoded as an array, while version filter handles installed_evra as a string. Now I have put a condition to handle the type accordingly.
2. System advisories and System packages were not persisting parameters as we were clearing the store on unmount. I have removed clearing the store.

Without hot refresh

---

src/SmartComponents/PackageSystems/PackageSystems.js

1. missing export button is added to package systems page
2. unwanted checkbox on empty table is removed

Package detail

---

src/App.scss
src/PresentationalComponents/Snippets/DescriptionWithLink.js

fix(Advisories): SPM-1100 make advisory description font consistent

---

src/App.scss
src/Messages.js
src/PresentationalComponents/Filters/SystemStaleFilter.js
src/PresentationalComponents/StatusReports/SystemsStatusReport.js
src/Utilities/Helpers.js
src/Utilities/api.js
src/Utilities/constants.js
src/store/Reducers/SystemsStore.js

Regressions are resolved:
1. Spinner is changed to Skeleton on load
2. the space between status cards are made 24 px
3. Icons are made 'md' size
4. status filter wording are made consistent with the mockups
5. double filters chips are fixed. now stale filter chips are only one fresh and one stale
6. status filters are sharable using URL params
https://user-images.githubusercontent.com/59481011/130784860-014d48d2-53cc-4b17-a604-35a795b7f587.mp4

fix(SystemtatusBar): regressions are resolved

---

package-lock.json
package.json

1.  SPM-1141: CVE-2021-3749 is remediated by updating Axios version from 0.21.1 to 0.21.4
2. SPM-1093: CVE-2021-32803 is remediated by updating deps in the dependency tree using 'npm audit fix'
3. SPM-1094: CVE-2021-32804 is remediated by updating deps in the dependency tree using 'npm audit fix'

chore(deps): vulnerabilities are remediated

---

src/Messages.js
src/PresentationalComponents/StatusReports/AdvisoriesStatusReport.js
src/SmartComponents/Advisories/Advisories.js

I have a few suggestions already added into the UI design: 
1. Move advisory name into the title position of the Patternfly card
2. move the number of applicable systems into a separate block GridItem  so that it is not split into 2 lines
3. Move os name to first column Grid item elements so that we have a balanced number of info labels into 2 sides.
I have not put a loader, because I am not sure if we have always more than 4 advisories in the database. If we always have and we know what will be shown, the loader can be put always

feat(AdvisoriesReport): SPM-1167 add most impactfull advisory info

---

src/PresentationalComponents/TableView/TableFooter.js
src/PresentationalComponents/TableView/TableView.js
src/PresentationalComponents/TableView/__snapshots__/TableView.test.js.snap
src/SmartComponents/AdvisoryDetail/__snapshots__/CveModal.test.js.snap
src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/AdvisorySystems/__snapshots__/AdvisorySystem.test.js.snap
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
src/SmartComponents/Systems/Systems.js

Should be working in all parts of Patchman

fix(SPM-1381): Pagination dropdown disabled when table empty

---

.travis/custom_release.sh

After Node.js upgrade to  version 16, Travis CI build is failing. @leSamo had already this situation and suggested writing custom release. The PR is inspired by [Vulnerability](https://github.com/RedHatInsights/vulnerability-ui/blob/master/.travis/custom_release.sh). I am not familiar with Travis, so any improvements are highly welcome.

chore(Travis): add custom release scripts

---

src/SmartComponents/PatchSetWizard/InputFields/SelectExistingSets.js
src/Utilities/Hooks.js
src/Utilities/api.js

We need to send  distinct requests for updating and creating a patch set according to the changed [API docs](https://console.stage.redhat.com/beta/docs/api/patch#operations-default-createBaseline). The API doc is missing description field on both endpoints:
1. For creating a patch set (**/api/patch/v1/baselines**): 
`{
"config": {
"to_time": "2022-12-31T12:00:00-04:00"
},
"inventory_ids": [
"string"
],
"name": "string"
}` 
2. For updating a patch set (**/api/patch/v1/baselines/{baseline_id}**):
```
{
"config": {
"to_time": "2022-12-31T12:00:00-04:00"
},
"inventory_ids": {
"additionalProp1": true,
"additionalProp2": true,
"additionalProp3": true
},
"name": "my-changed-baseline-name"
}
```

fix(PatchSetWizard): separate request to update and create set

---

package-lock.json
package.json
src/Routes.js
src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/Systems/System.test.js
src/SmartComponents/Systems/SystemListAssets.test.js
src/SmartComponents/Systems/Systems.js
src/SmartComponents/Systems/SystemsListAssets.js
src/SmartComponents/Systems/__snapshots__/System.test.js.snap
src/Utilities/Helpers.js
src/Utilities/Hooks.js
src/Utilities/constants.js

The PR enables using Unleash feature flags provided by the platform to manage path-sets feature. Current version of the Unleash is old, thus we are using only default enablement strategy. It only enables or disables the flag for now. There is a [ticket](https://issues.redhat.com/browse/APPSRE-3449) to upgrade its version. 
In order to enable/disable the flag you would need access to [Unleash instance](https://insights-stage.unleash.devshift.net/#/features/strategies/patch.patch_set) provided by app-sre. You will need to add these lines to your app-sre profile.
- $ref: /teams/insights/roles/insights-stage-unleash-admin.yml
- $ref: /teams/insights/roles/insights-unleash-admin.yml
- $ref: /teams/insights/roles/unleash-proxy.yml
For the sake of simplicity, you can test the PR by simply hard …

feat(PatchSet): put patch set work under feature flag

---

src/Messages.js
src/Routes.js
src/SmartComponents/PatchSetWizard/WizardAssets.js
src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/SystemDetail/__snapshots__/InventoryDetail.test.js.snap
src/SmartComponents/Systems/Systems.js
src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/DataMappers.js
src/Utilities/Helpers.js
src/store/Reducers/SystemDetailStore.js

This PR will add:
-  patch set info on Inventory detail header.
-  status and patch status filters into Review systems table in the patch set wizard.
-  default filters into Review systems table  in the patch set wizard.
-  patch set column into Review systems table  in the patch set wizard.
- remove feature flags for the Patch set table.

Integrate patch set

---

src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
src/Utilities/Helpers.js

This resolves: https://issues.redhat.com/browse/SPM-1461.
To repoduce the issue: 
1. Open the patch set wizard
2. Proceed to Review Systems step
3. Active multiple filter with a light speed
4. Hit on the 'Reser filters' button. At this step, the wizard should break and close.

chore(ReviewSystems): fix filters breaking the page

---

src/SmartComponents/SystemDetail/InventoryDetail.js

Resolves: https://issues.redhat.com/browse/SPM-1492. I am not able to do API request other than the type GET, theoratically just adding `patchSetState.shouldRefresh` to the the hook dependency should do the trick, most probably. Thus, please run this PR locally to make sure it does the fix.
To reproduce:
1. Assign system to a patch set via action on system detail page
2. The page continues to display old patch set name a needs to be refreshed to display new patch set name

fix(SPM-1492): system details page refreshs after patch-set change

---

src/Messages.js
src/SmartComponents/PatchSetWizard/PatchSetWizard.js
src/SmartComponents/PatchSetWizard/WizardAssets.js
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/SystemDetail/__snapshots__/InventoryDetail.test.js.snap
src/SmartComponents/Systems/Systems.js
src/SmartComponents/Systems/SystemsListAssets.js

Resolves: 
1. [Editing a patch set created wizard named 'Create patch set'](https://issues.redhat.com/browse/SPM-1490). Wizard title is renamed to 'Edit patch set'
2. [Assigning system to a patch set created wizard named 'Create patch set'](https://issues.redhat.com/browse/SPM-1493) Wizard title is renamed to 'Assign system(s) to a patch set'.
3. ['Assign to patch sets' action should be 'Assign to a patch set' (singular form).](https://issues.redhat.com/browse/SPM-1489) (all occurrances in Systems page)

fix(SPM-1490, SPM-1493): wizard texts updated

---

src/SmartComponents/PatchSetWizard/WizardAssets.js

This resolves: 
https://issues.redhat.com/browse/SPM-1487.
Initially PM asked to prevent users creating patch sets with zero systems. However, during the latest meeting team we agreed to remove the revert this case and remove the validation. Now, wizard lets users go through the step 2 even if no system is selected.
to reproduce: 
1. Go to Patch set page: https://console.stage.redhat.com/beta/insights/patch/patch-set
2. Click 'Create Patch Set' button
3. Fill the name and date, click next.
4. System selection is displayed, 'Next' button is greyed out. There's no way how to complete Patch Set creation.
Similarly, this PR enables patch sets with zero systems assigned to be edited. This bug is tracked: https://issues.redhat.com/browse/SPM-1491. 
To reproduce SPM-1491:
1. Edit a patch set …

fix(SPM-1487): let users create patch sets with zero systems assigned

---

src/Messages.js

I am not sure what the title should be, but there was a missing message causing a blank page after assigning a patch set.

fix(PatchSetWizard): Adding missing message

---

src/Messages.js

@gabipodolnikova I have found why patchSetTitle got disappeared. I mistakenly mutated it into three new messages by copying and changing. I am sometimes not really attentive :).

chore(Messages): fix invalid message IDs

---

src/Messages.js
src/SmartComponents/Modals/UnassignSystemsModal.js
src/SmartComponents/Modals/UnassignSystemsModal.test.js
src/SmartComponents/Modals/__snapshots__/UnassignSystemsModal.test.js.snap
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/SystemDetail/__snapshots__/InventoryDetail.test.js.snap
src/SmartComponents/Systems/System.test.js
src/SmartComponents/Systems/Systems.js
src/SmartComponents/Systems/SystemsListAssets.js
src/SmartComponents/Systems/__snapshots__/System.test.js.snap
src/Utilities/api.js
src/Utilities/constants.js

Resolves: https://issues.redhat.com/browse/SPM-1488. I am not able to make any other API requests except GET. Thus please make sure that API handles request nicely.
There are 2 use cases where users can remove system(s) from patch sets.
To reproduce from table row actions:
1. Go to Systems page
2. Click on 'Remove from patch set' row action of a system which has a set assigned.
3. The confirmation with the system number should appear
4. When users clicks on Remove button on the modal, system should be unassigned from the patch set
To reproduce from table toolbar dropdown:
1. Go to Systems page
2. Select as many systems as you want
3. Click on 'Remove from patch set' button from the tabletoolbars dropdown.
4. The confirmation with the system number should appear
5. When users clicks on …

fix(SPM-1488): remove systems from patch sets

---

src/Utilities/api.js
src/Utilities/api.test.js

The PR is intended to passdown api error response to the smart components. An error response is used to detect error status and handle correspondingly inside Smart components. e.g ([Systems.js](https://github.com/RedHatInsights/patchman-ui/blob/master/src/SmartComponents/Systems/Systems.js#L212) receives error status code and passes that to [ErrorHandler](https://github.com/RedHatInsights/patchman-ui/blob/master/src/PresentationalComponents/Snippets/ErrorHandler.js) ). Furthermore, redundant user checking before an api call is removed.
It also refactors test coverage code for api.js:
- disabled eslint rules are removed
- first test case for JSON response is removed as it is not necessary anymore
- some dirty code cleanup.

fix(api): errors from api response are passed down to components

---

src/PresentationalComponents/TableView/TableView.js
src/SmartComponents/Systems/Systems.js
src/store/Reducers/InventoryEntitiesReducer.js
src/store/Reducers/InventoryEntitiesReducer.test.js

This will hide the table toolbar when there is an some error.
Before: 
After:

fix(TableView): wrap table toolbar with ErrorHandler

---

src/Messages.js
src/SmartComponents/PatchSetWizard/InputFields/ToDateField.js
src/SmartComponents/PatchSetWizard/InputFields/ToDateField.test.js
src/SmartComponents/PatchSetWizard/WizardAssets.js
src/Utilities/dateValidator.js
src/Utilities/dateValidator.test.js

This is to improve date field validation and introduce start limit.
To check locally:
- make sure that the date input does not let users select a date prior to 1990.01.01
- make sure that input field validates: wrong date, date input format

fix(Date): improve validation, introduce date start limit

---

src/SmartComponents/PatchSetWizard/WizardAssets.js
src/SmartComponents/PatchSetWizard/steps/RequestProgress.js
src/Utilities/Hooks.js
src/store/index.js

This adds an error notification when a user tries to create a patch template with a name that already exists.
to reproduce:
1. Click on the Templates nav,
2. Randomly choose an existing template name from the table,
3. Click on the 'Create a template' button on the table toolbar.
4. Create a patch template with the name that you have chosen.
5. After you click on the 'Submit' button on the last step, an error notification should pop up.

chore(PatchTemplate): add notifications when api req fails

---

src/Routes.js
src/SmartComponents/PatchSetWizard/InputFields/ToDateField.js
src/SmartComponents/PatchSetWizard/PatchSetWizard.js
src/SmartComponents/PatchSetWizard/WizardAssets.js
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/SystemDetail/InventoryDetail.test.js
src/SmartComponents/Systems/System.test.js
src/SmartComponents/Systems/Systems.js

Introduces a feature flag again for all patch template work and fixes the wizard title bug.
Please verify:
1. When you click on the 'Templates' nav, the page gets redirected to the Advisories page(landing page).
2. Systems page has no 'Assign to patch set' button, Patch template column, and row actions do not include any action related to patch templates.
3. Inventory details header has no patch template name and no actions in the dropdown.
4. On The last step in the wizard after a patch template has been created/edited/assigned, the wizard title dynamically changes. Please refer video below:
[screencast-2022-07-19-132703.webm](https://user-images.githubusercontent.com/59481011/179709041-021c8902-e726-42a6-b081-2451d842e9e9.webm)

chore(PatchTemplate): put all patch template work under a feature flag and fix wizard title bug

---

src/Utilities/Hooks.js

Use the isBeta flag from chrome instead of unleash until unleash becomes mature.

chore(Unleash): disable unleash usage and use isBeta flag

---

src/Utilities/Helpers.js
src/Utilities/api.js
src/Utilities/useRemediationDataProvider.js

This fixes the remediation on the Systems page after it broke because of the new pagination enabled on `/view/advisories/systems `endpoint. Now remediation issue pairs are fetched from` /view/systems/advisories`, then passed to the Remediation module. 
To test:
1. Visit the systems page
2. Select one or more systems
3. Click on remediation
4. Observe that the request to fetch remediation pairs is made to /view/systems/advisories
5. Remediation modal does not brake
6. You can remediate selected system advisories

Fix remediations

---

src/SmartComponents/Advisories/Advisories.test.js
src/Utilities/useRemediationDataProvider.js
src/Utilities/useRemediationDataProvider.test.js

This will enable paginating the request to fetch remediation pairs on Systems and Advisories pages.
To test:
1. Visit the advisories page
2. bulk select a page/all rows
3. click on Remediate
4. Observe that there are multiple requests made to fetch paginated result
5. Observe that those results are being aggregated correctly
6. Observe that Remediation modal opens up as expected and you can successfully remediate
7. Please do so on the Systems page as well.

feat(SPM-1707): paginate remediation pair fetching

---

.eslintrc.yml
.travis.yml
config/cypress.webpack.config.js
cypress.config.js
cypress/support/component-index.html
cypress/support/component.js
package-lock.json
package.json
src/PresentationalComponents/Header/HeaderBreadcrumbs.cy.js

This PR installs cypress-related dependencies and makes sure we can run component tests. The cypress bundle is now also included to the Test stage in Travis CI (this doesn't modify pr_check since we are not changing `verify` npm script).

Support component tests

---

src/SmartComponents/SystemAdvisories/SystemAdvisories.js
src/SmartComponents/SystemDetail/SystemDetail.js
src/SmartComponents/SystemDetail/SystemDetail.test.js
src/SmartComponents/SystemDetail/__snapshots__/SystemDetail.test.js.snap
src/SmartComponents/SystemPackages/SystemPackages.js
src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/Helpers.js
src/Utilities/Hooks.js

This enables to open the Packages tab directly by clicking the package number on the Systems page.
To test:
1. Visit the Systems page,
2. click on a package number in the table
3. Observe that the packages tab is opened by default.
4. In any other case, the advisor tab is active by default.
5. When systems detail page is opened using URL, advisor tab should be active, page should not break.

feat(SPM-624): open packages tab directly from systes page.

---

src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/PackageSystems/PackageSystems.test.js

Fixes: [SPM-1802](https://issues.redhat.com/browse/SPM-1802) by sending the expected remediation issue ID according to the new validation.
To test:
1. Visit the packages page
2. click on any package name and open the details 
3. select some systems which have updatable package evra version
4. observe that the remediation modal is loaded & works as expected.

fix(SPM-1802): pass correct remediation issue ID

---

src/AppEntry.js
src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/Systems/Systems.js
src/store/index.js

Associated Jira ticket: #RHCLOUD-23128
The function `getRegistry` is no longer needed, on contrary with module federation it can bring additonal problems because of incorrect access of a store instance. This PR removes the usage of said function and replaces it with proper `store.replaceReducer` function.
Run patch locally and test if everything works as before (pay closer attention to pages with inventory in them).

chore(RHCLOUD-23128): Remove get registry dependency and use create store directly

---

src/SmartComponents/PatchSet/PatchSet.js

Associated Jira ticket: # (SPM-[1768](https://issues.redhat.com/browse/SPM-1768))
This adds a new role to the allow list of roles that can create/edit patch templates. Admin has access to everything, and I had set it so that only admin can perform template actions. The custom role should have access too it as well. This change allows both admin and a user with patch:template:write permissions to perform template actions
Navigate the Templates page with an account that has patch:template:write access and read permissions, and verify that you can create and edit a template
Do the same for an account with admin permissions
Verify that if a user with read permissions goes to the page they dont have access to the button and cant edit the templates.
If you need access to accounts with these …

fix(SPM-1768): Adds custom role to templates page

---

src/SmartComponents/PackageSystems/PackageSystems.js

Associated Jira ticket: No ticket needed
Removes unnecessary onSelect prop from Package systems table. This will prevent unwanted checkboxes on an empty table.
1. Visit the package page
2. click on a package to open details
3. search for non existing system to get empty table
4. observe that there are no any checkbox in the table rows

fix(PackageSystem): remove unneccessary onSelect prop

---

cypress/fixtures/api/patchSets.json
src/Messages.js
src/PresentationalComponents/Snippets/EmptyStates.js
src/PresentationalComponents/Snippets/EmptyStates.test.js
src/PresentationalComponents/Snippets/__snapshots__/EmptyStates.test.js.snap
src/SmartComponents/PatchSet/PatchSet.js
src/SmartComponents/PatchSet/PatchSet.test.js
src/SmartComponents/PatchSet/__snapshots__/PatchSet.test.js.snap
src/Utilities/Hooks.js
src/Utilities/Hooks.test.js

Associated Jira ticket: # [SPM-1770](https://issues.redhat.com/browse/SPM-1770)
As a permissioned user who does not have a Smart Management entitlement, when I try to visit Patch templates, I should see that this is Smart Management functionality and be given an opportunity to do something about that, so that I can check it out and decide if I want to buy Smart Management entitlements to keep using this awesome feature. 
I will try to create an account without smart management entitlement for testing the PR. I will update once I can create.
- A user with proper permissions, but on an account WITHOUT a Smart Management entitlement, should be see an entitlement blocker page when visiting /insights/patch/templates.
- A user with proper permissions and on an account WITH a Smart Management …

feat(SPM-1770): introduce smart management check for Templates page

---

package-lock.json
package.json
src/SmartComponents/SystemAdvisories/SystemAdvisories.js
src/Utilities/Helpers.js
src/Utilities/Helpers.test.js
src/Utilities/useOnSelect.js
src/Utilities/useOnSelect.test.js

Associated Jira ticket: # ([SPM-1838](https://issues.redhat.com/browse/SPM-1838))
Fixes the selection on the System advisories table by removing the unselected item completely from the selected rows object, instead of setting it to selected=falsy. Also, if expanded rows are ignored while turning a row as selected. 
1. This touches selection across pages, thus please play with it and try remediating your selected items.

fix(SPM-1838): remove unselected items completely, ignore expanded rows

---

.gitignore
.travis.yml
README.md
babel.config.js
coverage.sh
cypress.config.js
cypress/support/component.js
package-lock.json
package.json

This combines coverage reports from jest and cypress together before commiting them to codecov.
Associated Jira ticket: https://issues.redhat.com/browse/SPM-1826
Run tests locally, check that two coverage folders are generated, and then try  to run `npm run coverage`.

chore: Collect coverage from component tests

---

src/PresentationalComponents/AdvisoryHeader/AdvisoryHeader.js
src/PresentationalComponents/AdvisoryHeader/__snapshots__/AdvisoryHeader.test.js.snap
src/SmartComponents/AdvisoryDetail/AdvisoryDetail.js
src/SmartComponents/AdvisoryDetail/__snapshots__/AdvisoryDetail.test.js.snap

Associated Jira ticket: # [RHIF-160](https://issues.redhat.com/browse/RHIF-160)
The affected systems table has to wait for the header. There is no need to have this approach as error handling is done in the affected systems table as well.
This should not change functionality overall, just run the PR locally and verify that there is nothing weird in Advisory detail page.

chore(RHIF-160): decouple advisory detail header and table

---

deploy/frontend.yml
src/Messages.js
src/SmartComponents/PatchSet/PatchSet.js
src/SmartComponents/PatchSet/__snapshots__/PatchSet.test.js.snap
src/Utilities/constants.js

Associated Jira ticket: [SPM-1548](https://issues.redhat.com/browse/SPM-1548)
Associated mockup: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/ELywAxO
- update header title in Patch Templates page from 'Patch template' to 'Templates'.
- add popover next to header title
- update `frontend.yml` with current information
Verify correspondence of Template list page header with the [mockup](https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/ELywAxO).

feat(Templates): Update templates page header

---

src/PresentationalComponents/TableView/TableView.js
src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
src/store/Reducers/PatchSetsReducer.js

Associated Jira ticket: [SPM-1805](https://issues.redhat.com/browse/SPM-1805).
Filter, page and per page update did not work in the Patch templates table due to Redux updates not propagating. Also updated skeleton table to be compact if the loaded table is compact. Sorting does not work yet due to [SPM-1894](https://issues.redhat.com/browse/SPM-1894).
Try changing page, per page and filter in the Patch Templates page.
Filter did not always work. Page and per page update did not work at all.
Filter, page and per page update should now work.

fix: Fix patch templates page not receiving redux updates

---

src/PresentationalComponents/TableView/TableFooter.js
src/PresentationalComponents/TableView/TableView.js
src/PresentationalComponents/TableView/__snapshots__/TableFooter.test.js.snap
src/SmartComponents/AdvisoryDetail/__snapshots__/CveModal.test.js.snap
src/SmartComponents/Packages/__snapshots__/Packages.test.js.snap
src/SmartComponents/PatchSet/__snapshots__/PatchSet.test.js.snap
src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap

- fix bottom pagination using double padding (32px instead of 16px)
- fix paginations not being replaced by loading skeletons when data is loading (this fix applies to all pages except Inventory tables, which will be addressed in a separate PR); top pagination displayed stale data for the duration of the loading, bottom pagination was removed for the duration of the loading
Bottom pagination should have correct 16px padding. Top and bottom paginations of all tables except Systems (Inventory) tables should be replaced by 200px loading skeleton when table data is loading.

fix: Pagination fixes (loading skeletons, margins)

---

src/SmartComponents/SystemAdvisories/SystemAdvisories.js
src/SmartComponents/SystemAdvisories/SystemAdvisories.test.js
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/SystemDetail/InventoryDetail.test.js
src/SmartComponents/SystemDetail/SystemDetail.js
src/SmartComponents/SystemDetail/__snapshots__/InventoryDetail.test.js.snap
src/SmartComponents/SystemDetail/__snapshots__/SystemDetail.test.js.snap
src/SmartComponents/SystemPackages/SystemPackages.js
src/SmartComponents/SystemPackages/SystemPackages.test.js
src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
src/store/Reducers/SystemDetailStore.js
src/store/Reducers/SystemDetailStore.test.js
src/store/index.js

Associated Jira ticket: # [RHIF-171](https://issues.redhat.com/browse/RHIF-171)
This PR removes AppInfo federated module usage together with rendering the SystemDetail component using activeApps in redux. Thus, making the application's complexity and performance.
NEEDS TO BE MERGED AFTER: https://github.com/RedHatInsights/insights-inventory-frontend/pull/1766
Run both PRs together and make sure no app breaks. Basic functionality should not change. Observe that the system details page works as expected.

perf(RHIF-171): Get rid of activeApps in redux

---

src/SmartComponents/Modals/Helpers.js
src/SmartComponents/Modals/UnassignSystemsModal.js
src/SmartComponents/Modals/__snapshots__/UnassignSystemsModal.test.js.snap
src/SmartComponents/PatchSetDetail/PatchSetDetail.js
src/Utilities/DataMappers.js

Associated Jira ticket: [SPM-1904](https://issues.redhat.com/browse/SPM-1904), [SPM-1907](https://issues.redhat.com/browse/SPM-1907), [SPM-1927](https://issues.redhat.com/browse/SPM-1927)
From System list page:
It was not possible to remove template from stale systems. This is now fixed.
From Template detail page:
Add table row actions accessible with patch:template:write permission, these actions contain action to unassign system from a template.
**a) System list page:**
Find a system that has template assigned.
i) Unassign system from template using row actions kebab.
ii) Unassign multiple systems from template using bulk action kebab in the table toolbar. Make sure to try to select some systems that do have template and some that don't - modal should then point out to you that some …

Template system unassignment from Template detail page

---

src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/PatchSetDetail/PatchSetDetailAssets.js
src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/DataMappers.js
src/Utilities/api.js

- Link from Advisory detail to Template detail page
- Fix sorting on Template detail page
- Link from Template detail to Systems detail page
a) Go to Advisory detail page and in the table find a system that has a template. Verify you can navigate to Template detail page by clicking on the system name inside the table.
b) In Template detail page you should be able to correctly sort the table by display name. All other columns should have sorting indicators disabled.
c) Go to Template detail page and click on any system name inside the first column. You should be correctly navigated to Systems detail page of clicked system.

feat: Table links and sorting fix

---

src/Utilities/RemediationPairs.js
src/Utilities/useRemediationDataProvider.js

Associated Jira ticket: https://issues.redhat.com/browse/SPM-1885
Fixes failing remediation by passing auth token explicitly. After platform decomissioned auth cooki, we have to pass it to webworker.
Please make sure remediation works as expected, the remediation gets indeed created.

fix(SPM-1885): pass auth token to webworker

---

src/PresentationalComponents/Snippets/EmptyStates.js
src/SmartComponents/PatchSet/PatchSet.js
src/SmartComponents/PatchSet/__snapshots__/PatchSet.test.js.snap
src/SmartComponents/PatchSetWizard/PatchSetWizard.js
src/SmartComponents/PatchSetWizard/WizardAssets.js

As per PM's request (https://redhat-internal.slack.com/archives/CPS5FH07Q/p1678202549907769?thread_ts=1678119878.115079&cid=CPS5FH07Q) we are, for now, removing all documentation link related to templates.
These places include:
- Template list page empty state (displayed when user has 0 templates)
- Template list page title tooltip
- Template creation/editing wizard just below the wizard title

Remove template docs links

---

src/Utilities/DataMappers.js

The messages for corresponding columns were accidentally swapped.

Fix Template detail table advisory fallback text

---

src/Messages.js
src/SmartComponents/PatchSetWizard/PatchSetWizard.js
src/SmartComponents/PatchSetWizard/WizardAssets.js
src/SmartComponents/PatchSetWizard/steps/ConfigurationStepFields.js
src/SmartComponents/PatchSetWizard/steps/ReviewPatchSet.js
src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
src/SmartComponents/PatchSetWizard/steps/__snapshots__/ReviewPatchSet.test.js.snap

Associated Jira ticket: [SPM-1893](https://issues.redhat.com/browse/SPM-1893)
- until now the title of the step had to be the same for header label and sidebar label, but in the future we will need them to be different so I decoupled these strings by removing `showTitles: true` and manually adding header to each step
- update System selection step text to the [latest mockups](https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/eKRw04p)
- if user leaves description field empty, review step will state 'No description provided' instead of 'No description available'

Decouple step title and sidebar name in Template Wizard

---

src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/SystemDetail/InventoryDetail.test.js
src/Utilities/api.js
src/store/Reducers/SystemDetailStore.js

Associated Jira ticket: [SPM-1945](https://issues.redhat.com/browse/SPM-1945)
In System detail header
- update template name to link to Template detail page
- fix race condition where Inventory API response could overwrite `hasThirdPartyRepo` and `patchSetName` parameters and header would show up as having no template and no third party repo
- fix tags not displaying

Link from System detail header to template detail

---

src/SmartComponents/PatchSetDetail/PatchSetDetail.js
src/SmartComponents/PatchSetWizard/PatchSetWizard.js
src/SmartComponents/PatchSetWizard/WizardAssets.js

Associated Jira ticket: [SPM-1893](https://issues.redhat.com/browse/SPM-1893)
- if template has 0 systems it shows an empty state on template detail page, the button in the empty state now correctly opens wizard; previously it didn't do anything
- removed unused 'assign' template wizard type
- editing a template from template detail page now has correct "edit" verb instead of "create" in the titles

Template detail empty state button launches wizard

---

src/Utilities/Hooks.js

There was a bug when you assigned a system to a template in the system list table, the template would have the date-to reset to January 1, year 1. This has now been fixed.

Fix date-to resetting when assigning a system to template

---

src/Messages.js
src/PresentationalComponents/TableView/TableViewAssets.js
src/Utilities/api.js

See comment in [SPM-1948](https://issues.redhat.com/browse/SPM-1948)
- rename "Applicable systems" to "Affected systems" in table and dashbar
- update `advisories/` endpoint version from v2 to v3 to fix incorrect count of systems in applicable/affected systems column

Fix Advisory list page applicable system column

---

src/Messages.js
src/PresentationalComponents/Snippets/EmptyStates.js
src/PresentationalComponents/Snippets/EmptyStates.test.js
src/PresentationalComponents/Snippets/__snapshots__/EmptyStates.test.js.snap
src/SmartComponents/PatchSet/PatchSet.js
src/SmartComponents/PatchSet/PatchSet.test.js
src/SmartComponents/PatchSetDetail/PatchSetDetail.js

Associated Jira ticket: # ([ESSNTL-4496)](https://issues.redhat.com/browse/ESSNTL-4496)
This replaces all references of Red Hat Smart Manager with Satellite. I've left entitlements as is for the time being as thats user schema.
Just skim the code and UI for any references to smart manager and verify there are none the user can see.

feat(ESSNTL-4496): Replace SmartManager w/ satellite

---

src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js

See https://github.com/RedHatInsights/patchman-ui/pull/1028#pullrequestreview-1391792579
Bug that was fixed happened in Template modal -> System review step if you navigated to page 2 and then applied filter which returned less than 20 rows; calling page 2 on this data caused 400 error. Fixed by resetting to page 1 on every filter change, which is behaviour of all other Patchman tables (and Vulnerabilities as well).

Fix template modal system table not resetting to page 1

---

src/SmartComponents/PatchSet/PatchSet.js

See the right side of the screenshots.

Remove row actions kebab on empty state in Template list table

---

src/Routes.js

This un gates the templates routes completely.
1. Run the PR locally
2. open C.R.C with insights-qa acc on stage-beta env
3. navigate to /templates route from the left sidebar
4. observer that you are not redirected to /advisories route
5. Now open a new session on stage-stable env
6. navigate to /templates route as previously done
7. observe that you are not redirected to /advisories
8. The same procedure applies to /templates/:templateName route as well

fix: ungate the templates route

---

src/Utilities/DataMappers.js
src/Utilities/Helpers.js

If template system had OS data unavailable it only showed the blue icon. Correct behaviour is to show "N/A" and no blue icon. 
- go to https://stage.foo.redhat.com:1337/beta/insights/patch/templates/8264?page=4&perPage=20&sort=os
- observe OS column contents

Add fallback to OS column on Template detail page

---

src/PresentationalComponents/StatusReports/SystemsStatusReport.js
src/SmartComponents/Systems/__snapshots__/System.test.js.snap

https://issues.redhat.com/browse/SPM-2054
- stale system count used to display 0 instead of the correct amount, this was fixed by adding staleness param to the API request
- improved the responsivity of the dashbar
- fixed camel case `SystemsStatusreport` -> `SystemsStatusReport`

Fix stale system count in Dashbar

---

src/SmartComponents/Systems/SystemListAssets.test.js
src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/RemediationPairs.js

https://issues.redhat.com/browse/SPM-2069
1. Go to system list page
2. Find a system with a template, that has some applicable (non-installable) advisories
3. In row actions menu select "Apply all applicable advisories"
4. Observe how many issues are selected -- previously it selected applicable and installable advisories, now it should only select installable

Include only installable advisories when remediating all

---

src/SmartComponents/Advisories/Advisories.test.js
src/SmartComponents/AdvisorySystems/AdvisorySystem.test.js
src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/PackageSystems/PackageSystems.test.js
src/SmartComponents/SystemPackages/SystemPackages.test.js
src/SmartComponents/Systems/System.test.js
src/Utilities/Hooks.js
src/Utilities/useOnSelect.js
src/Utilities/useOnSelect.test.js

Steps to Reproduce:
Navigate to the Advosry details page
Apply status filter-select Applicable
then select all() from filter
This PR correctly avoids selecting systems with the status, "Applicable", which should be disabled. Also check this functionality by going to Inventory -> Systems -> choose a system -> Click Patch tab. This should show the same selection functionality.
This PR also fixes a bug not mentioned in the Jira card. There is a bug on Patch -> Systems where if you select a system and then you go to any page after page 1 and `Select all`, it will only select advisories on that page and after. It will not select any items on previous pages.
Please include steps to test …

fix(SPM-2055): Select all on disabled advisories

---

config/prod.webpack.config.js

Associated Jira ticket: # [(issue)](https://issues.redhat.com/browse/RHINENG-502)
As the app containerized build start getting used, we are required to precisely differentiate preview and stable builds. This makes it possible by adjusting the prod webpack config a bit.
Testing happens after gets merged

chore: verify preview env better in prod webpack config

---

src/PresentationalComponents/Snippets/ErrorHandler.js

Ticket: https://issues.redhat.com/browse/SPM-2131
Show correct empty state when 504 (Gateway timeout) is received in API response.

Handle 504 errors with correct empty state

---

src/Utilities/Helpers.js

To see what's broken check the 2 following advisories: RHBA-2023:2052
RHSA-2023:3246
We have 2 different ways that descriptions come in for Advisories. The most common way is to separate every line with `\n\n`. This would create double space between each line. To remedy this, we have a `preserveNewlines` function in `Helpers.js` that removes the extra `\n`.
But, the new variation of description correctly provides `\n\n` for paragraph separations and only `\n` for bullet separations. But with the current `preserveNewlines` functionality, it removes the `\n` for the bullets, making them appear as a single line (see RHBA-2023:2052).
This PR adds an additional function that takes the substring of the description that includes the bullets and replaces any `\n\n` with a single `\n`, ignoring …

fix(RHINENG-391): Create func for various newline scenarios

---

package.json

This should remove semantic-release commits and stop triggering CI twice for them. Copy-pasted from Inventory

chore: Align semantic release config

---

src/PresentationalComponents/TableView/TableViewAssets.js
src/SmartComponents/SystemPackages/__snapshots__/SystemPackages.test.js.snap
src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/DataMappers.js

Status column in `System detail page > Packages table` and `Packages detail page > Systems table` is now sortable.

Make package status columns sortable

---

src/store/Reducers/AdvisoryListStore.js
src/store/Reducers/AdvisoryListStore.test.js

Associated Jira ticket: [#SPM-1623](https://issues.redhat.com/browse/SPM-1623)
Current page is always set to 1 in the URL on Advisories Page, even though the current presented page value it is being handled by a PF4 Pagination component inside the page 
(the 'page' parameter from the queryParams in the AdvisoryListStore is not used).
It was suggested on the ticket by Jiri that the page parameter should be removed completely from the URL
After a conversation with Sebastian, we have decided to also remove page_size from queryParam, because we already handle offset & limit in the URL which have the same purposes of page & page_size
Insure the component is working correctly, even without the missing 'page' & 'page_size' parameters from the queryParams.
Old URL of the 1st page, with 'page' & …

AdvisoriesPage - Remove unused 'page' parameter from queryParams in the AdvisoryListStore

---

src/PresentationalComponents/Filters/OsVersionFilter.js
src/PresentationalComponents/Filters/OsVersionFilter.test.js

Associated Jira ticket: [RHINENG-1260](https://issues.redhat.com/browse/RHINENG-1260)
When reloading the page the `currentValue` is loaded from the URL and is an `array`. But when you apply an OS filter through the UI it is an `string`. I've added a check for an array so the page doesn't crash.
In the systems table apply an OS filter and refresh, the load should be successful.

fix(RHINENG-1260): OS filter works after refresh

---

src/SmartComponents/Systems/SystemListAssets.test.js
src/SmartComponents/Systems/SystemsListAssets.js

https://issues.redhat.com/browse/SPM-2085
On the System list page the "Installable advisories" column used to say "No applicable advisories" instead of "No installable advisories" when the system had no advisories.

Fix System list installable advisories empty state text

---

src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/DataMappers.js

https://issues.redhat.com/browse/RHINENG-2485
How to test:
- Make sure "Managed by Satellite" text with tooltip according to the mockup is inside Template column for systems with "satellite_managed: true" attribute in the following tables
- Systems list
- Advisory system list
- Package system list
- Systems table inside Template Wizard > Apply to systems step

Show "Managed by Satellite" in place of Template name

---

README.md
config/dev.webpack.config.js
package-lock.json
package.json

no jira.
This is a quick PR that aims to make npm run start* scripts consistent across Insights frontend applications.

chore: Update npm run start scripts and documentation

---

src/Messages.js
src/SmartComponents/Modals/AssignSystemsModal.js
src/SmartComponents/Modals/Helpers.js
src/SmartComponents/Modals/UnassignSystemsModal.js
src/SmartComponents/Modals/useUnassignSystemsHook.js
src/SmartComponents/PatchSet/PatchSetAssets.js
src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/Systems/SystemsListAssets.js

Ticket: https://issues.redhat.com/browse/RHINENG-2489
Mockups: https://www.sketch.com/s/598ac9a1-16ce-47b1-8515-e79928a2b2fb/a/P19w2K1
- Disable row action kebab items related to templates on System list table, but do not disable row checkbox (since Remediation is allowed)
- Disable row action kebab items related to templates in System detail header
- Update Template assignment and removal modals to handle some Satellite managed systems being selected.
- Make sure Systems table in Template wizard contains only Systems not managed by Satellite

Do not allow template application for Satellite managed systems

---

src/Utilities/Helpers.js
src/Utilities/Helpers.test.js
src/Utilities/SystemHelpers.test.js
src/Utilities/SystemsHelpers.js

Associated Jira ticket: https://issues.redhat.com/browse/RHINENG-1836.
This makes the "Group" column sortable on two views: /patch/systems and /patch/advisories/%id.
The Inventory change is not yet merged to ensure that the tenant apps support sorting first and avoid breaking change.
1. Pull this Inventory PR locally https://github.com/RedHatInsights/insights-inventory-frontend/pull/2070.
2. Run Patch with this PR `npm run start -- --port=8004`
3. Run Inventory with `LOCAL_APPS=patch:8004~http npm run start:proxy`
4. Navigate to the updated views (in stage-stable environment) and make sure you can sort by system groups.
5. Check the URL search parameters too: while sorting the table, and then refreshing the page - the same sorting must be applied. …

feat(RHINENG-1836): Make group column sortable

---

package-lock.json
package.json
src/Utilities/axiosInterceptors.js

Fixes https://issues.redhat.com/browse/RHINENG-8635
Axios did have an [error handler refactoring](https://github.com/axios/axios/pull/3645) in [0.27.0](https://github.com/axios/axios/releases/tag/v0.27.0), therefore I had to change the accessor to `isAxiosError`.

chore(deps): Update axios to fix CVE

---

src/PresentationalComponents/Filters/PackagesListStatusFilter.js
src/PresentationalComponents/Filters/PackagesListStatusFilter.test.js
src/Utilities/api.js
src/Utilities/constants.js
src/Utilities/hooks/Hooks.test.js

Associated Jira ticket: # [(issue)](https://issues.redhat.com/browse/RHINENG-8745)
This fixes the broken packages page by updating the Patch status filter key from system_updatable which is obsolete to the new systems_applicable
1. Visit the packages page
2. Observe that the page works as expected and the table is filtered by **Systems with patches available** by default
3. From the filters dropdown find **Patch status** filter
4. Play with it, make sure it works correclt

fix(RHINENG-8745): update patch status filter keys

---

src/SmartComponents/Remediation/AsyncRemediationButton.js
src/SmartComponents/Systems/SystemsTable.js
src/Utilities/constants.js

Change wording in NoDataModal when a system with no advisories is remediated
Associated Jira ticket: RHINENG-3123
1. Run this PR with https://github.com/RedHatInsights/insights-remediations-frontend/pull/408
2. Go to Patch systems page
3. Select system with no advisories available
4. The modal should have changed wording

change(RemediationButton):RHINENG-3123 text for no advisory systems

---

src/Utilities/api.js

Updates the request content-type from application/json to application/vnd.api+json. After the vulnerability api has upgraded their connexion package, application/json type is no longer supported

fix(RHINENG-8948): update request content-type for vulnerability api calls

---

package-lock.json
package.json
src/PresentationalComponents/Header/__snapshots__/Header.test.js.snap
src/SmartComponents/AdvisoryDetail/__snapshots__/AdvisoryDetail.test.js.snap
src/SmartComponents/AdvisorySystems/AdvisorySystemsTable.test.js
src/SmartComponents/Systems/SystemTable.test.js
src/Utilities/hooks/Hooks.js

Associated Jira ticket: #944 tps://issues.redhat.com/browse/RHINENG-9035
Fixes the loading icon in bulk select by updating the fec-config package. It also includes tiny changes to cleanup bulk select config. The icons on systems tables will be fixed by https://github.com/RedHatInsights/insights-inventory-frontend/pull/2192
1. Navigate to Advisories table
2. Select all items in the table
3. Observe that there is now the spinner icon while items are being selected and selection dropdown is disabled

fix(RHINENG-9035): bulk select all icon fixed

---

src/PresentationalComponents/Snippets/EmptyStates.js
src/SmartComponents/PatchSet/PatchSet.js
src/SmartComponents/PatchSetWizard/PatchSetWizard.js
src/SmartComponents/PatchSetWizard/WizardAssets.js
src/SmartComponents/PatchSetWizard/steps/ConfigurationStepFields.js
src/Utilities/constants.js

- removed commented in docs template link that was planned, but later scrapped
- removed dead code in `ConfigurationStepFields` which was unreachable due to `shouldShowRadioButtons = false;`, this code was only used for migrations between two development versions of Template wizard

refactor(TemplateWizard): Remove obsolete code

---

src/SmartComponents/Systems/SystemListAssets.test.js
src/SmartComponents/Systems/SystemsListAssets.js
src/Utilities/SystemHelpers.test.js

Associated Jira ticket: No ticket needed
A small fix for the double icons on the package systems page. As the page completely uses the inventory table and also there were extra column definition, double icons appeared. Removing the extra one fixes it.
I am not sure even if this icon should be displayed in package systems table. I will consult it with the ux.

fix: double icons in  display name column on package systems table

---

src/SmartComponents/AdvisorySystems/AdvisorySystems.js
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/Systems/SystemsTable.js
src/Utilities/Helpers.js
src/Utilities/Helpers.test.js
src/Utilities/SystemsHelpers.js

This fixes issues with syncing the state and URL of filters in the Systems table.

fix(OperatingSystemFilter): RHINENG-10345 - Fix OS inventory filter conversion

---

config/setupTests.js
src/Routes.js
src/SmartComponents/AdvisorySystems/AdvisorySystemsTable.js
src/SmartComponents/Modals/Helpers.js
src/SmartComponents/Modals/UnassignSystemsModal.js
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/PatchSetDetail/PatchSetDetail.js
src/SmartComponents/PatchSetWizard/WizardAssets.js
src/SmartComponents/PatchSetWizard/steps/ReviewSystems.js
src/SmartComponents/SystemDetail/InventoryDetail.js
src/SmartComponents/Systems/SystemListAssets.test.js
src/SmartComponents/Systems/SystemTable.test.js
src/SmartComponents/Systems/SystemsListAssets.js
src/SmartComponents/Systems/SystemsMainContent.js
src/SmartComponents/Systems/SystemsMainContent.test.js
src/SmartComponents/Systems/SystemsTable.js
src/Utilities/DataMappers.js
src/Utilities/SystemsHelpers.js
src/store/Reducers/SystemDetailStore.js

Associated Jira ticket: [HMS-5033](https://issues.redhat.com/browse/HMS-5033)
Goal: 
[This](https://issues.redhat.com/browse/RHINENG-7807)  caused all of the patch template UI to be removed, and all systems list references to either be removed or to start using the new content template data
All of this now should been controlled with a feature flag  🫤 
Acceptance Criteria:
Old UI for patch and patch templates exists in stable
Patch uses the new content templates in preview, old patch templates are not available
Stable patch UI can be flipped from the old  templates to new templates in the future easily
Run with proxy against prod, test changes by toggling preview on and off on various screens.
Original list of changes can be found [here](https://issues.redhat.com/browse/RHINENG-7807). …

Fixes 5033: Expose old patch templates UI via feature flag

---

NOTICE

As per my email thread, I'd like to comply with the license appendix and add a NOTICE file specifying the owner of the copyright.

fix(license): add NOTICE file specifying Red Hat as the owner

---

package-lock.json
package.json
src/PresentationalComponents/TableView/TableView.js
src/PresentationalComponents/TableView/TableViewAssets.js
src/SmartComponents/Advisories/Advisories.js
src/SmartComponents/Packages/Packages.js
src/SmartComponents/SystemAdvisories/SystemAdvisories.js
src/SmartComponents/SystemDetail/__snapshots__/SystemDetail.test.js.snap
src/SmartComponents/SystemPackages/SystemPackages.js

https://issues.redhat.com/browse/RHINENG-3138

feat: Add column management

---

cypress.config.js
fec.config.js
package-lock.json
package.json

According to the discussion we had on slack -> we need to remove webpack deps because we don't need it
Also, I added missing unstable spdy to fec config

chore(deps): remove webpack dependancies because they are not needed

---

src/SmartComponents/AdvisorySystems/AdvisorySystemsTable.js
src/SmartComponents/PackageSystems/PackageSystems.js
src/SmartComponents/Systems/SystemListAssets.test.js
src/SmartComponents/Systems/SystemsListAssets.js
src/SmartComponents/Systems/SystemsTable.js
src/Utilities/SystemHelpers.test.js
src/Utilities/SystemsHelpers.js

This is a necessary prerequisite for Column management implementation. This allows us to simply change properties of table columns retrieved from Inventory (display name, workspaces (groups), tags, last seen).
Obsolete function `systemsColumnsMerger` will be removed together with old template pages.

chore: Declarative column merging

---

src/SmartComponents/Systems/SystemsListAssets.js

https://issues.redhat.com/browse/RHINENG-15545
The tooltip was added to the Inventory last seen column, but we were overwriting the column with our title due to intl, but it's not needed anymore. The column header will have tooltip only after RedHatInsights/insights-inventory-frontend#2429 has been merged.

feat(RHINENG-15545): Consume last seen column from Inventory
